### ISSUE TITLE
user auth checklist

### ISSUE THREAD

**Issue by zhz364** [zhz364/HiCamp#2]
# User Auth
## Functionality
- [x] The main button with logo should link to `/`
- [x] Has working demo login
- [x] Smooth, bug free navigation
### Before Login
- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [ ] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user
### After Login
- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in
## Style
- [x] The site should look exactly like the actual site
- [x] All relevant elements should have `cursor: pointer` on hover
- [x] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [ ] Remove Redux logger and all console.log()'s from production
## Seeds
- [x] Adequate and appropriate seeds

**Comment by ghost** [comment]
Hey Zhang Zhang, good job on user auth! there are just a few things id like to comment on.  First, when you go from login to sign up the errors persist and we don't want that.  Second, it looks like the signup form is not centered and moves a lot lower than the login when I transition between the two.  Let's go ahead and make sure that the signup form is centered so that it doesnt move when we transition.

**Comment by ghost** [comment]
looks good Zhang Zhang please reference this to remove the redux logger from production https://open.appacademy.io/learn/swe-in-person/full-stack-project/getting-your-app-production-ready
